name: The Fallen Body
favicon: null
layout_spectrum: 0.51173
typography_spectrum: 0.23556
title: "Taylor's Book Pub"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a1b2bc'
    - '#060604'
    - '#e7e8e2'
    - '#708a97'
    - '#4b6c11'
  brandStrength: 0.8027497893199325
  lightness: 0.695554903941229
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
